import "@t007/utils";
import type { FieldOptions } from "@t007/input";

/** Shared options for alert, confirm, and prompt dialogs. */
export interface DialogOptions {
  /** Unique identifier for the dialog for programmatic dismissal. Auto-generated by default. */
  id?: string;
  /** Text for the confirmation button. @default  "OK". */
  confirmText?: string;
  /** Text for the cancel button where applicable. @default  "Cancel". */
  cancelText?: string;
  /** Browser behavior for handling dialog closure. @default  "any". */
  closedBy?: HTMLDialogElement["closedBy"];
  /** Render dialog inside a specific root element instead of document body. */
  rootElement?: HTMLElement | null;
  /** Whether to restrict interactions to `rootElement` if provided. @default  `true`. */
  scoped?: boolean;
}

// BUNDLE EXPORTS & GLOBAL DECLARATIONS

/** Check if a dialog is currently active. Optionally check for a specific dialog by id.
 * @param id Optional unique identifier of the dialog to check.
 * @return `true` if the specified dialog (or any dialog when no id is provided) is active, otherwise `false`.
 */
export function isActive(id?: string): boolean;
/** Show an alert dialog and resolve when the user confirms.
 * @param message Message shown in the dialog body.
 * @param options Optional dialog configuration.
 * @returns Promise that resolves to the user choice.
 */
export function alert(message: string, options?: DialogOptions): Promise<boolean>;
/** Show a confirm dialog and resolve with the user choice.
 * @param question Question shown in the dialog body.
 * @param options Optional dialog configuration.
 * @returns Promise that resolves to true when confirmed.
 */
export function confirm(question: string, options?: DialogOptions): Promise<boolean>;
/** Show a prompt dialog and resolve with the entered value.
 * @param question Question shown in the dialog body.
 * @param defaultValue Initial value for the prompt input.
 * @param options Optional dialog configuration.
 * @returns Promise that resolves to the entered string or null.
 */
export function prompt(question: string, defaultValue?: string, options?: DialogOptions & FieldOptions): Promise<string | null>;
/** Dismiss a dialog by id or all dialogs when no id is provided.
 * @param id Optional unique identifier of the dialog to dismiss. If not provided, all dialogs will be dismissed.
 * @param response Optional value to resolve the dialog's promise with. If not provided, defaults to `true` for confirm and alert dialogs, and `null` for prompt dialogs.
 */
export function dismiss(id?: string, response?: any): void;

interface Dialog {
  isActive(id?: string): boolean;
  alert(message: string, options?: DialogOptions): Promise<boolean>;
  confirm(question: string, options?: DialogOptions): Promise<boolean>;
  prompt(question: string, defaultValue?: string, options?: DialogOptions & FieldOptions): Promise<string | null>;
  dismiss(id?: string, response?: any): void;
}

declare global {
  interface T007Namespace {
    /** Browser alert helper. */
    alert: typeof alert;
    /** Browser confirm helper. */
    confirm: typeof confirm;
    /** Browser prompt helper. */
    prompt: typeof prompt;
    /** Dialog management object. */
    dialog: Dialog;
  }
  interface Window {
    Alert?: T007Namespace["alert"];
    Confirm?: T007Namespace["confirm"];
    Prompt?: T007Namespace["prompt"];
  }
}
